[package]
name = "lorawan"
version = "0.1.0"
edition = "2021"

[lib]
test = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heapless = "0.7.5"
as-slice = "0.2"
generic-array = "0.14.2"
aes = { version = "0.8.2" }
cmac = { version = "0.7.2" }
futures = { version = "0.3.17", default-features = false }
async-trait = "0.1.64"
defmt = { version = "0.3.0", optional = true }

[dev-dependencies]
mockall = "0.11.4"


[features]
default = []
defmt = ["dep:defmt"]
