[package]
name = "lorawan"
version = "0.1.0"
edition = "2021"

[lib]
test = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heapless = "0.7.5"
as-slice = "0.2"
generic-array = "0.14.2"
aes = { version = "0.6.0" }
cmac = { version = "0.5.1" }
futures = { version = "0.3.17", default-features = false }
async-trait = "0.1.64"
defmt = { version = "0.3.0", optional = true }
postcard = { version = "1.0.4" }
serde = { version = "1.0.158", default-features = false }

[dev-dependencies]
mockall = "0.11.4"


[features]
default = ["defmt"]
defmt = ["dep:defmt", "postcard/use-defmt"]
