[package]
name = "lorawan"
version = "0.1.0"
edition = "2021"
test = false
bench = false


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heapless = "0.7.5"
as-slice = "0.2"
generic-array = "0.14.2"
aes = { version = "0.6.0" }
cmac = { version = "0.5.1" }
# defmt = { version = "0.3.0", optional = true }
futures = { version = "0.3.17", default-features = false }
async-trait = "0.1.64"
rand_core = { version = "0.6.2", default-features = false }
# serde = { version = "1.0.145", default-features = false, features = [
#     "derive",
# ], optional = true }
# lorawan = { version = "0.7.1", path = "../rust-lorawan/encoding", default-features = false, features = [
#     "serde",
#     "defmt",
#     "default-crypto",
#     "with-downlink",
# ] }
