[package]
name = "lorawan"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/lucasgranberg/lorawan"
categories = ["embedded", "no-std", "asynchronous"]
keywords = ["lorawan", "lora", "radio", "iot", "semtech"]
description = "Provides end device support for LoRaWAN revision 1.0.4."

[lib]
test = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heapless = "0.7.16"
as-slice = "0.2"
generic-array = "0.14.2"
aes = { version = "0.8.3", optional = true }
cmac = { version = "0.7.2", optional = true }
futures = { version = "0.3.28", default-features = false }
defmt = { version = "0.3", optional = true }
serde = { version = "1.0", default-features = false, features = ["derive"], optional = true}
lora-modulation = "0.1.3"

[features]
default = ["default-crypto", "defmt","serde"]
defmt = ["dep:defmt","lora-modulation/defmt"]
default-crypto = ["aes", "cmac"]
serde = ["dep:serde"]