[package]
name = "lorawan"
version = "0.1.0"
edition = "2021"

[lib]
test = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heapless = "0.7.5"
as-slice = "0.2"
generic-array = "0.14.2"
aes = { version = "0.8.2", optional = true }
cmac = { version = "0.7.2", optional = true }
futures = { version = "0.3.17", default-features = false }
defmt = { version = "0.3.0", optional = true }
lora-phy = { version = "1" }

[dev-dependencies]
mockall = "0.11.4"

[features]
default = ["default-crypto", "defmt"]
defmt = ["dep:defmt"]
default-crypto = ["aes", "cmac"]

[patch.crates-io]
lora-phy = { path = "../lora-phy" }
