#[target.thumbv7em-none-eabi]
# rustflags = ["-g", "-C", "link-arg=-Tdefmt.x"]
# uncomment this to make `cargo run` execute programs on QEMU
# runner = "qemu-system-arm -cpu cortex-m3 -machine lm3s6965evb -nographic -semihosting-config enable=on,target=native -kernel"

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
#runner = "probe-run --chip STM32WLE5CCUx --connect-under-reset -v"
#runner = "probe-run --chip STM32WL55JCIx --connect-under-reset -v"
runner = "probe-rs run --chip STM32WLE5JCIx"

[build]
target = "thumbv7em-none-eabi"

[env]
DEFMT_LOG = "trace"

[bin]
test = false
bench = false
